In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Importing necessary Python libraries
import pandas as pd

In [3]:
# Loading dataset into a pandas DataFrame
# Displaying first few rows to understand structure

In [4]:
data = pd.read_csv('cafe.csv', encoding='latin1')

In [5]:
data.head(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [7]:
 # Converting to integer

In [8]:
data['Quantity'] = pd.to_numeric(data['Quantity'], errors='coerce')

In [9]:
data['Price Per Unit'] = pd.to_numeric(data['Price Per Unit'], errors='coerce')

In [10]:
data['Total Spent'] = pd.to_numeric(data['Total Spent'], errors='coerce')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

In [12]:
# Dropping rows with missing values

In [13]:
data=data.dropna(subset=['Quantity'])

In [14]:
data.isnull().sum()

Transaction ID         0
Item                 315
Quantity               0
Price Per Unit       515
Total Spent          482
Payment Method      2447
Location            3109
Transaction Date     150
dtype: int64

In [15]:
# Calculating price per unit for each transaction

In [16]:
data['Price Per Unit']= data['Total Spent']/ data['Quantity']

In [17]:
data.isnull().sum()

Transaction ID         0
Item                 315
Quantity               0
Price Per Unit       482
Total Spent          482
Payment Method      2447
Location            3109
Transaction Date     150
dtype: int64

In [18]:
data.head(30)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,NaN,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.0,NaN,NaN,UNKNOWN,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,ERROR
30,TXN_1736287,NaN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02

In [19]:
# Replace missing category with 'Unknown'

In [20]:
data['Item'] = data['Item'].replace(['ERROR', ' ', '',], 'UNKNOWN')

In [21]:
data.columns = data.columns.str.strip()
data['Item'] = data['Item'].fillna('UNKNOWN')

In [22]:
data.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit       482
Total Spent          482
Payment Method      2447
Location            3109
Transaction Date     150
dtype: int64

In [23]:
data.head(30)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,NaN,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,UNKNOWN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,UNKNOWN,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.0,NaN,NaN,UNKNOWN,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,ERROR
30,TXN_1736287,UNKNOWN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02

In [24]:
# Defining default item prices and filling missing 'Price Per Unit' values based on item name

In [25]:
prices={
    'Cake':3.0,
    'Smoothie':4.0,
    'Cookie':1.0,
    'Juice':3.0,
    'Sandwich':4.0,
    'Salad':5.0,
    'Tea':1.5,
    'Coffee':2.0,
}

def fill(row):
    if pd.isna(row['Price Per Unit']):
        return prices.get(row['Item'], row['Price Per Unit'])
    else:
        return row['Price Per Unit']

In [26]:
data['Price Per Unit'] = data.apply(fill, axis=1)

In [27]:
data.head(50)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,UNKNOWN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,UNKNOWN,2.0,1.5,3.0,NaN,In-store,2023-03-21
15,TXN_2847255,Salad,3.0,5.0,15.0,Credit Card,In-store,2023-11-15
16,TXN_3765707,Sandwich,1.0,4.0,4.0,NaN,NaN,2023-06-10
17,TXN_6769710,Juice,2.0,3.0,6.0,Cash,In-store,2023-02-24
18,TXN_8876618,Cake,5.0,3.0,15.0,Cash,ERROR,2023-03-25
19,TXN_3709394,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-01-15
21,TXN_3567645,Smoothie,4.0,4.0,16.0,Credit Card,Takeaway,2023-03-30
22,TXN_5132361,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,2023-12-01
23,TXN_2616390,Sandwich,2.0,4.0,8.0,NaN,NaN,2023-09-18
24,TXN_9400181,Sandwich,5.0,4.0,20.0,Cash,In-store,2023-06-03
25,TXN_7958992,Smoothie,3.0,4.0,NaN,UNKNOWN,UNKNOWN,2023-12-13
26,TXN_5183041,Cookie,5.0,1.0,5.0,Credit Card,In-store,2023-04-20
27,TXN_5695074,Juice,4.0,3.0,12.0,Credit Card,Takeaway,2023-04-10
28,TXN_8467949,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-11
29,TXN_7640952,Cake,4.0,3.0,12.0,Digital Wallet,Takeaway,ERROR
30,TXN_1736287,UNKNOWN,5.0,2.0,10.0,Digital Wallet,NaN,2023-06-02
31,TXN_8927252,UNKNOWN,2.0,NaN,NaN,Credit Card,ERROR,2023-11-06
32,TXN_9677376,Smoothie,4.0,4.0,16.0,NaN,In-store,2023-08-15
33,TXN_7710508,UNKNOWN,5.0,1.0,5.0,Cash,NaN,ERROR
34,TXN_8853997,Smoothie,2.0,4.0,8.0,Digital Wallet,Takeaway,2023-10-09
35,TXN_9130559,Sandwich,1.0,4.0,4.0,Credit Card,UNKNOWN,2023-05-28
36,TXN_6855453,UNKNOWN,4.0,3.0,12.0,NaN,In-store,2023-07-17
37,TXN_1080432,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-29
38,TXN_2655815,Smoothie,4.0,4.0,16.0,NaN,Takeaway,2023-06-08
39,TXN_6688524,Coffee,4.0,2.0,8.0,ERROR,NaN,2023-06-29
40,TXN_2083138,Smoothie,3.0,4.0,12.0,NaN,In-store,2023-04-17
41,TXN_2427584,Sandwich,4.0,4.0,16.0,NaN,Takeaway,2023-12-22
42,TXN_6650263,Tea,2.0,1.5,NaN,NaN,Takeaway,2023-01-10
43,TXN_9620080,Juice,4.0,3.0,12.0,NaN,Takeaway,2023-10-02
44,TXN_1491578,Cookie,2.0,1.0,2.0,NaN,NaN,2023-02-23
45,TXN_5455792,Salad,3.0,5.0,15.0,Cash,NaN,2023-03-22
46,TXN_8078640,Juice,4.0,3.0,12.0,Digital Wallet,In-store,2023-11-03
47,TXN_9499313,Juice,5.0,3.0,15.0,NaN,NaN,2023-03-02
48,TXN_8201146,Juice,5.0,3.0,15.0,Cash,NaN,2023-06-26
49,TXN_8230936,Cake,3.0,3.0,9.0,NaN,ERROR,2023-05-02
50,TXN_7742742,Cake,5.0,3.0,15.0,NaN,Takeaway,2023-09-05

In [28]:
data.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit        50
Total Spent          482
Payment Method      2447
Location            3109
Transaction Date     150
dtype: int64

In [29]:
# Calculate total amount spent per transaction

In [30]:
data['Total Spent']=data['Quantity']*data['Price Per Unit']

In [31]:
data.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit        50
Total Spent           50
Payment Method      2447
Location            3109
Transaction Date     150
dtype: int64

In [32]:
# Count and display the number of items labeled as 'UNKNOWN'

In [33]:
unknown_count = (data['Item'] == 'UNKNOWN').sum()
print(unknown_count)

910

In [34]:
data= data.dropna(subset=['Total Spent'])

In [35]:
data.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2435
Location            3091
Transaction Date     150
dtype: int64

In [36]:
unknown_count = (data['Item'] == 'UNKNOWN').sum()
print(unknown_count)

860

In [37]:
# Create a copy of the dataset for backup or further use

In [38]:
data3=data.copy()

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9471 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9471 non-null   object
 1   Item              9471 non-null   object
 2   Quantity          9471 non-null   float64
 3   Price Per Unit    9471 non-null   float64
 4   Total Spent       9471 non-null   float64
 5   Payment Method    7036 non-null   object
 6   Location          6380 non-null   object
 7   Transaction Date  9321 non-null   object
dtypes: float64(3), object(5)
memory usage: 665.9+ KB

In [40]:
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
data['Payment Method'].value_counts(dropna=False)

Payment Method
NaN               2435
Digital Wallet    2170
Credit Card       2158
Cash              2143
ERROR              287
UNKNOWN            278
Name: count, dtype: int64

In [42]:
data['Payment Method'] = data['Payment Method'].replace(['ERROR', 'UNKNOWN', ' ', '  '], 'Unknown')
data['Payment Method'] = data['Payment Method'].fillna('Unknown')

In [43]:
data['Payment Method'].value_counts(dropna=False)

Payment Method
Unknown           3000
Digital Wallet    2170
Credit Card       2158
Cash              2143
Name: count, dtype: int64

In [44]:
data.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method         0
Location            3091
Transaction Date     150
dtype: int64

In [45]:
data['Location'].value_counts(dropna=False)

Location
NaN         3091
In-store    2870
Takeaway    2849
ERROR        339
UNKNOWN      322
Name: count, dtype: int64

In [46]:
data['Location'] = data['Location'].replace(['ERROR', 'UNKNOWN', ' ', '  '], 'Unknown')
data['Location'] = data['Location'].fillna('Unknown')

In [47]:
data['Location'].value_counts(dropna=False)

Location
Unknown     3752
In-store    2870
Takeaway    2849
Name: count, dtype: int64

In [48]:
# Convert 'Transaction Date' column to datetime format

In [49]:
data['Transaction Date'] = pd.to_datetime(data['Transaction Date'], errors='coerce')

In [50]:
data.isnull().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    434
dtype: int64

In [51]:
data.head(15)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,Unknown,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,Unknown,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,Unknown,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,Unknown,2023-10-28
8,TXN_4717867,UNKNOWN,5.0,3.0,15.0,Unknown,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,Unknown,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,NaT
12,TXN_7619095,Sandwich,2.0,4.0,8.0,Cash,In-store,2023-05-03
13,TXN_9437049,Cookie,5.0,1.0,5.0,Unknown,Takeaway,2023-06-01
14,TXN_8915701,UNKNOWN,2.0,1.5,3.0,Unknown,In-store,2023-03-21

In [52]:
# Fill missing transaction dates using forward fill

In [53]:
data['Transaction Date'] = data['Transaction Date'].ffill()

In [54]:
data.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [55]:
total_sales=data['Total Spent'].sum()
total_sales

np.float64(84744.0)

In [56]:
data['Month'] = data['Transaction Date'].dt.month

In [57]:
# Extract month name from the transaction date

In [58]:
data['Month_Name'] = data['Transaction Date'].dt.strftime('%B')

In [59]:
data = data.sort_values('Month')

In [60]:
# Create abbreviated month name (first three letters)

In [61]:
data['Month_Abbr'] = data['Month_Name'].str[:3]

In [62]:
data.tail(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Month,Month_Name,Month_Abbr
4985,TXN_3324387,UNKNOWN,1.0,4.0,4.0,Credit Card,Unknown,2023-12-13,12,December,Dec
9983,TXN_9226047,Smoothie,3.0,4.0,12.0,Cash,Unknown,2023-12-30,12,December,Dec
9986,TXN_2858441,Sandwich,2.0,4.0,8.0,Credit Card,In-store,2023-12-14,12,December,Dec
25,TXN_7958992,Smoothie,3.0,4.0,12.0,Unknown,Unknown,2023-12-13,12,December,Dec
4986,TXN_7603895,Smoothie,5.0,4.0,20.0,Credit Card,In-store,2023-12-13,12,December,Dec